### DISCUSSION TITLE
No internet connection after being authentified

### DISCUSSION THREAD

**Discussion by Nelse74** [strongswan/strongswan#1070] [Q&A]
Good morning,

I'm using strongswan (5.9.5) with the eap-radius plugin. The freeradius (3.0.2) is joined to a samba AD that use ntlm_auth with mschapv2 to connect the users connecting to the vpn.

It's working great. Except that i'm missing something with the redirecting of the packets because there is no internet connection after the client is authenticated.

Here are my conf files :

ipsec.conf
```
config setup

  uniqueids=never

conn %default
  auto=add
  compress=no
  type=tunnel
  keyexchange=ikev2
  fragmentation=yes
  forceencaps=yes
  mobike=yes
  rekey=yes

  ike=aes256-sha256-ecp384,aes256-sha384-prfsha384-ecp384!
  esp=aes256gcm16-ecp384,aes256!

conn branchet
  left=%any
  leftid=X.X.X.X #Public IP
  leftcert=server-cert.pem
  leftsendcert=always
  leftsubnet=0.0.0.0/0

  right=%any
  rightid=%any
  rightauth=eap-radius
  rightsourceip=10.10.10.0/24
  eap_identity=%any
  rightsendcert=never
  rightdns=8.8.8.8,8.8.4.4
```

strongswan.conf
```
charon {
                load_modular = yes
                        plugins {
                                include strongswan.d/charon/*.conf
                eap-radius {
                        accounting = yes
                        servers {
                freeradius {
                address = X.X.X.X #Internal IP
                secret = testing123
                auth_address = 1812
                acct_address = 1813
                }
                }
                }
                }
                include strongswan.d/*.conf
                }
```

ipsec.secret 
```
# ipsec.secrets - strongSwan IPsec secrets file
 : RSA server-key.pem
```

firewalld
```
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: ens4
  sources: 
  services: cockpit dhcpv6-client ipsec ssh
  ports: 500/udp 4500/udp 80/tcp
  protocols: 
  forward: no
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
	rule protocol value="ah" accept
	rule protocol value="esp" accept
```

Freeradius and strongswan are on the same machine, that's why I put public IP and internal IP.
I've added masquerade to allow NAT, but maybe i'm missing a rule ?
I've read https://docs.strongswan.org/docs/5.9/features/natTraversal.html but it didn't really lead me closer to the problem.
Actually i'd like for the packet to be routed to an internal subnet after the client logs in. I've looked around but didn't find an option like that to add to ipsec.conf or swanctl.conf.
There is some element i'm still unfamiliar with in strongswan...
I've also looked at https://www.strongswan.org/testing/testresults/ikev2/rw-eap-peap-radius/moon.iptables, and i noticed some forward rules that I find in a lot of iptable configuration for strongswan. I didn't find any other method for firewalld for the rules, maybe I should translate the forward rules to firewalld ?

Thanks in advance for any lead or tips, have a wonderful tuesday.
