### DISCUSSION TITLE
Routing Issue: Packets Not Going Through IPSec Tunnel in OpenVPN and StrongSwan Setup

### DISCUSSION THREAD

**Discussion by TeaTimeJP2** [strongswan/strongswan#1797] [Q&A]
I have configured a single VPS (Rocky Linux 9) with two types of VPN connections using OpenVPN and StrongSwan. OpenVPN is used to assign IP addresses in the range of 10.8.0.0/24 to clients. Meanwhile, StrongSwan is used to establish a Site-to-Site VPN (PSK).

In the StrongSwan configuration file (swanctl.conf), the local traffic selector (local_ts) is set as 10.8.0.0/24, and the remote traffic selector (remote_ts) is set as 192.168.128.0/18.

Strongswan's IPSec counterpart is the Yamaha RTX1210.
The result of "ping 10.8.0.1" from RTX1210 has a reply from OpenVPN 10.8.0.1.

However, I am encountering a problem. When a client connected through OpenVPN executes "ping 192.168.150.1", the packet doesn't traverse the IPSec tunnel but is routed directly onto the internet. These packets should ideally follow the StrongSwan settings and go through the IPSec tunnel.

So, my question is, how can I ensure these packets (particularly those headed to the destination that matches the remote traffic selector) are correctly routed via the IPSec tunnel?

Please let me know if you need any other information.

sysctl -p
`net.ipv4.ip_forward = 1` 

strongswan.conf and swanctl.conf
I have set according to this URL [https://www.strongswan.org/testing/testresults6/ikev2/net2net-psk/](https://www.strongswan.org/testing/testresults6/ikev2/net2net-psk/)

swanctl --list-sas
swanctl --stats
swanctl --list-conns
ip -s xfrm policy
ip -s xfrm state
ip route list table 220
Output as per this URL [https://www.strongswan.org/testing/testresults6/ikev2/net2net-psk/](https://www.strongswan.org/testing/testresults6/ikev2/net2net-psk/)

These commands have different output from this URL [https://www.strongswan.org/testing/testresults6/ikev2/net2net-psk/](https://www.strongswan.org/testing/testresults6/ikev2/net2net-psk/)
iptables -L
```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination    
```

iptables-save
```
# Generated by iptables-save v1.8.8 (nf_tables) on Sun Jul 16 03:56:58 2023
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -s 10.8.0.0/24 -o eth0 -j MASQUERADE
COMMIT
```

something else that might be related
firewall-cmd --list-all
```
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: eth0
  sources: 
  services: cockpit dhcpv6-client ipsec openvpn ssh
  ports: 443/tcp 500/udp 4500/udp
  protocols: 
  forward: yes
  masquerade: yes
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```
