### DISCUSSION TITLE
Save-Keys error

### DISCUSSION THREAD

**Discussion by DavideDeZuane** [strongswan/strongswan#2659] [Q&A] [answered]
I am running strongswan inside a container since I would like to make a minimal initiator that communicates with strongswan. In order to determine if the two peers derive the same secret and in general to verify the correctness of the derived keys before implementing them, it is convenient for me to dump the keys using the save-keys plugin.
I followed the configuration as per the documentation and this is loaded correctly, it also prints the warning message telling me the path where they will be saved. However when I do the init exchange the ike2_decryption_table file is not generated. 
Can anyone help me with this.

### Dockerfile

```
FROM ubuntu:latest
ENV VERSION=6.0.0
# Install dependencies
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y \
    libgmp-dev \
    libssl-dev \
    libcurl4-openssl-dev \
    libsystemd-dev \
    make \
    gcc \
    g++ \
    flex \
    wget \
    bzip2 \
    bison \
    libcap-ng-dev \
    iproute2 \
    iptables \
    autoconf \
    automake \
    libtool \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

RUN wget https://download.strongswan.org/strongswan-${VERSION}.tar.bz2 && tar xjf strongswan-${VERSION}.tar.bz2 
WORKDIR /strongswan-${VERSION}
RUN ./configure --prefix=/usr --sysconfdir=/etc \
	--with-systemdsystemunitdir \
	--enable-save-keys  \
	--enable-charon         \
	--enable-systemd        \
	--enable-ikev2          \
	--enable-vici           \
	--enable-swanctl        \
    	--enable-nonce          \
	--enable-random         \
	--enable-drbg           \   
	--enable-openssl        \    
	--enable-curl           \
	--enable-pem            \
	--enable-x509           \
	--enable-constraints    \
   	--enable-pubkey         \   
	--enable-socket-default \
	--enable-kernel-netlink \
	--enable-resolve        

RUN make && make install
```
### Docker-compose
```
services:
  vpn-server:
    build: .
    container_name: strongswan
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_MODULE
    stdin_open: true
    tty: true
    volumes:
      - "./log:/var/log"
      - "./swanctl:/etc/swanctl"
      - "./strongswan.conf:/etc/strongswan.conf"
    command: ["sh", "-c", "/usr/libexec/ipsec/charon"]
```
### Strongswan.conf

```
charon {

  load_modular = yes
  #load = random nonce openssl pem pkcs1 curl vici kernel-netlink socket-default updown pubkey save-keys
 
  port = 500
  port_nat_t = 4500
  #remove some notify payload
  send_vendor_id = no
  keepalive = 0s
  multiple_authentication = no
  follow_redirects = no
  signature_authentication = no
  init_limit_half_open = 5
  ikesa_limit = 5


  plugins {
    include strongswan.d/charon/*.conf
  	save-keys {
      		load = yes
		  ike = yes
		  wireshark_keys = /var/log
	  }
  
  }
}
```
### Log

```
Feb  7 15:35:46 00[DMN] !! WARNING: SAVING IKE KEYS TO '/var/log'
```
