### DISCUSSION TITLE
Unable to route client traffic through strongSwan

### DISCUSSION THREAD

**Discussion by gabrielvachon** [strongswan/strongswan#376] [General]
Hi!
My goal is to connect a client from Windows 10 with EAP-MSCHAPv2 to strongSwan and get on the internet through it. I'd only have to reach the server and the web.

I am able to connect myself on the server and receive an IP address from the pool I configured but I am unable to reach anything except the server. The server cannot ping my PC.

Here are my configurations:
_public IP : 1.2.3.4
domain name : domain.example.com_

**strongswan.conf**
```
swanctl {
  load = pem pkcs1 x509 revocation constraints pubkey openssl random
}

charon-systemd {
  load = random nonce aes des md4 sha1 sha2 fips-prf pem pkcs1 curve25519 gmp x509 curl revocation hmac vici k$
}
```

**swanctl.conf**
```
connections {

   rw-eap-mschapv2 {
      local_addrs  = 1.2.3.4
      pools = mobile-pool

      local {
         certs = fullchain.pem
         id = domain.example.com
      }
      remote-windows {
         auth = eap-mschapv2
         eap_id = %any
      }
      children {
         net {
            local_ts  = 1.2.3.4/32

            updown = /usr/local/libexec/ipsec/_updown iptables
            esp_proposals = aes256-sha1
         }
      }
      version = 2
      send_certreq = no
      proposals = aes256-sha256-modp1024,aes256-sha256-modp2048
   }
}

secrets {
   eap-xxxxxxxx {
      id = xxxxxxxx
      secret = "xxxxxxx"
   }
}

pools {
   mobile-pool {
      addrs = 10.1.2.10-10.1.2.20
      dns = 8.8.8.8
      subnet = 0.0.0.0/0
   }
}

include conf.d/*.conf
```

**firewall-cmd --list-all --zone=drop**
```
drop (active)
  target: DROP
  icmp-block-inversion: no
  interfaces: eth0
  sources:
  services: http https ipsec ssh
  ports: 500/udp 4500/udp
  protocols:
  masquerade: yes
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:
        rule protocol value="esp" accept
        rule protocol value="ah" accept

```

**Comment by tobiasbrunner** [comment]
You configured `local_ts  = 1.2.3.4/32`, so only the server itself is reachable through the tunnel (if the client actually does that, some will bypass the tunnel when reaching the server to avoid IKE traffic going through the tunnel too).

if you want to tunnel everything, use `local_ts = 0.0.0.0/0` instead.

**Reply by gabrielvachon** [reply]
Hi, thank you for the quick reply!

I've set `local_ts = 0.0.0.0/0` like you recommended. Everything should pass through the tunnel. But it seems like strongSwan still can't forward my packets to the web...

**Reply by gabrielvachon** [reply]
Problem solved.

In firewalld, I added the subnet 10.1.2.0/24 in the trusted zone, it is now able to reach the web.

**firewall-cmd --zone=trusted --add-source=10.1.2.0/24**
```
trusted (active)
  target: ACCEPT
  icmp-block-inversion: no
  interfaces:
  sources: 10.1.2.0/24
  services:
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:

```
