### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [strongswan/strongswan#2123]
ref: https://monitor.f-droid.org/builds/log/org.strongswan.android/81#site-footer

Ah, easy... let me bump NDK... umm OpenSSL does not build with 26, will use 2 versions then:
```
  - versionName: 2.5.0
    versionCode: 81
    commit: 4be75c5ab14a9983cc075a7a65ce4a4f4717f805
    subdir: src/frontends/android/app
    sudo:
      - apt-get update
      - apt-get install -y automake bison flex gettext gperf libtool make pkg-config
      - apt-get install -y openjdk-17-jdk-headless
      - update-java-alternatives -a
    gradle:
      - yes
    srclibs:
      - OpenSSL@OpenSSL_1_1_1t
    prebuild:
      - sdkmanager 'ndk;21.4.7075529'
      - sed -i -e "/clean.dependsOn 'cleanNative'/d" build.gradle
    scandelete:
      - testing
    build:
      - lib="$PWD/src/main/jni/openssl"
      - export ANDROID_NDK_HOME=$$SDK$$/ndk/21.4.7075529
      - export PATH=/opt/android-sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/opt/android-sdk/tools:/opt/android-sdk/platform-tools:/opt/gradle/bin
      - pushd $$OpenSSL$$
      - export CC=armv7a-linux-androideabi16-clang
      - ./Configure android-arm no-shared no-ssl3 no-engine no-dso no-asm no-hw no-comp
        no-stdio -fPIC -DOPENSSL_PIC -D__ANDROID_API__=16 -ffast-math -O3 -funroll-loops
      - make -j $(nproc)
      - mkdir -p "${lib}/armeabi-v7a"
      - cp libcrypto.a ${lib}/armeabi-v7a/
      - make distclean
      - export CC=aarch64-linux-android21-clang
      - ./Configure android-arm64 no-shared no-ssl3 no-engine no-dso no-asm no-hw
        no-comp no-stdio -fPIC -DOPENSSL_PIC -D__ANDROID_API__=21 -ffast-math -O3
        -funroll-loops
      - make -j $(nproc)
      - mkdir -p "${lib}/arm64-v8a"
      - cp libcrypto.a ${lib}/arm64-v8a/
      - make distclean
      - export CC=i686-linux-android16-clang
      - ./Configure android-x86 no-shared no-ssl3 no-engine no-dso no-asm no-hw no-comp
        no-stdio -fPIC -DOPENSSL_PIC -D__ANDROID_API__=16 -ffast-math -O3 -funroll-loops
      - make -j $(nproc)
      - mkdir -p "${lib}/x86"
      - cp libcrypto.a ${lib}/x86/
      - make distclean
      - export CC=x86_64-linux-android21-clang
      - ./Configure android-x86_64 no-shared no-ssl3 no-engine no-dso no-asm no-hw
        no-comp no-stdio -fPIC -DOPENSSL_PIC -D__ANDROID_API__=21 -ffast-math -O3
        -funroll-loops
      - make -j $(nproc)
      - mkdir -p "${lib}/x86_64"
      - cp libcrypto.a ${lib}/x86_64/
      - cp -R include/ ${lib}/
      - make distclean
      - popd
      - export ANDROID_NDK_HOME=/opt/android-sdk/ndk/26.1.10909125
      - export PATH=/opt/android-sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/opt/android-sdk/tools:/opt/android-sdk/platform-tools:/opt/gradle/bin
      - echo "LOCAL_PATH := \$(call my-dir)" >"${lib}/Android.mk"
      - echo "include \$(CLEAR_VARS)" >>"${lib}/Android.mk"
      - echo "LOCAL_MODULE := libcrypto_static" >>"${lib}/Android.mk"
      - echo "LOCAL_SRC_FILES := \$(TARGET_ARCH_ABI)/libcrypto.a" >>"${lib}/Android.mk"
      - echo "LOCAL_EXPORT_C_INCLUDES := \$(LOCAL_PATH)/include" >>"${lib}/Android.mk"
      - echo "include \$(PREBUILT_STATIC_LIBRARY)" >>"${lib}/Android.mk"
      - cd ../../../../
      - ./autogen.sh
      - ./configure --disable-defaults --verbose
      - make dist -j $(nproc)
    ndk: 26.1.10909125
```

ok... we juggle versions... OpenSSL builds... but then 
```
...
~/build/org.strongswan.android/src/frontends/android/app
+ export ANDROID_NDK_HOME=/opt/android-sdk/ndk/26.1.10909125
+ ANDROID_NDK_HOME=/opt/android-sdk/ndk/26.1.10909125
+ export PATH=/opt/android-sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/opt/android-sdk/tools:/opt/android-sdk/platform-tools:/opt/gradle/bin
+ PATH=/opt/android-sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/opt/android-sdk/tools:/opt/android-sdk/platform-tools:/opt/gradle/bin
+ echo 'LOCAL_PATH := $(call my-dir)'
+ echo 'include $(CLEAR_VARS)'
+ echo 'LOCAL_MODULE := libcrypto_static'
+ echo 'LOCAL_SRC_FILES := $(TARGET_ARCH_ABI)/libcrypto.a'
+ echo 'LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/include'
+ echo 'include $(PREBUILT_STATIC_LIBRARY)'
+ cd ../../../../
+ ./autogen.sh
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4/config'.
libtoolize: copying file 'm4/config/libtool.m4'
libtoolize: copying file 'm4/config/ltoptions.m4'
libtoolize: copying file 'm4/config/ltsugar.m4'
libtoolize: copying file 'm4/config/ltversion.m4'
libtoolize: copying file 'm4/config/lt~obsolete.m4'
configure.ac:376: installing './compile'
configure.ac:379: installing './config.guess'
configure.ac:379: installing './config.sub'
configure.ac:24: installing './install-sh'
configure.ac:24: installing './missing'
fuzz/Makefile.am: installing './depcomp'
configure.ac: installing './ylwrap'
+ ./configure --disable-defaults --verbose
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether UID '1000' is supported by ustar format... yes
checking whether GID '1000' is supported by ustar format... yes
checking how to create a ustar tar archive... gnutar
checking whether make supports nested variables... (cached) yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for a sed that does not truncate output... /usr/bin/sed
checking configured UDP ports (500, 4500)... ok
checking for gcc... x86_64-linux-android21-clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/home/vagrant/build/org.strongswan.android':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```

odd I'll enter the VM, retry `./configure` but now it works, what....??? whatever

we'll come back later, carry on
```
$ cd src/frontends/android/app
$ gradle assembleRelease
...
> Task :app:configureNdkBuildRelease[arm64-v8a] FAILED
> Task :app:lintVitalAnalyzeRelease

FAILURE: Build failed with an exception.

```
full log: 
[log.log](https://github.com/strongswan/strongswan/files/14408098/log.log)

Umm, now what?

**Comment by tobiasbrunner** [comment]
> Ah, easy... let me bump NDK

Note that we now have the NDK version set in `ndkVersion` in build.gradle.

> ... umm OpenSSL does not build with 26 ...
> - OpenSSL@OpenSSL_1_1_1t

Why use OpenSSL 1.1.1 and not OpenSSL 3.x? (I know newer versions of OpenSSL 3.x [currently don't build](https://github.com/openssl/openssl/pull/22181) with the NDK, but otherwise 3.x builds fine with 26.1.10909125). We also provide a [build script for OpenSSL](https://github.com/strongswan/strongswan/blob/master/src/frontends/android/openssl/build.sh). It uses Docker by default, but that can be disabled via `NO_DOCKER=1`.

Also note that running `autogen.sh`, `configure` and `make dist` is only to generate some files (e.g. parsers etc.) in the source directory when building from the repository (as compared to a release tarball, which contains these generated files). This is not meant to be run with the NDK. The build eventually failed because one of the generated files (oid.c, which is generated from oid.txt with a Perl script) was missing.

**Comment by licaon-kter** [comment]
right 3.2.1 hits https://github.com/openssl/openssl/pull/22181 _(do we want to patch it like https://github.com/android/ndk/issues/1992#issuecomment-1910723059 ?)_

downgraded to 3.1.2 for now

recipe
```
  - versionName: 2.5.1
    versionCode: 82
    commit: b21178b43ced84c091ee15541035db5bcc6b280c
    subdir: src/frontends/android/app
    sudo:
      - apt-get update
      - apt-get install -y automake bison flex gettext gperf jq libtool make pkg-config
      - apt-get install -y openjdk-17-jdk-headless
      - update-java-alternatives -a
    gradle:
      - yes
    srclibs:
      - OpenSSL@openssl-3.1.2
    prebuild: sed -i -e "/clean.dependsOn 'cleanNative'/d" build.gradle
    scandelete:
      - testing
    build:
      - export ANDROID_NDK_ROOT=$$NDK$$
      - export ANDROID_NDK_HOME=$$NDK$$
      - export lib="$PWD/src/main/jni/openssl"
      - export script="$PWD/../openssl"
      - pushd $$OpenSSL$$
      - OUT_DIR=$lib $script/compile.sh
      - popd
      - echo "LOCAL_PATH := \$(call my-dir)" >"${lib}/Android.mk"
      - echo "include \$(CLEAR_VARS)" >>"${lib}/Android.mk"
      - echo "LOCAL_MODULE := libcrypto_static" >>"${lib}/Android.mk"
      - echo "LOCAL_SRC_FILES := \$(TARGET_ARCH_ABI)/libcrypto.a" >>"${lib}/Android.mk"
      - echo "LOCAL_EXPORT_C_INCLUDES := \$(LOCAL_PATH)/include" >>"${lib}/Android.mk"
      - echo "include \$(PREBUILT_STATIC_LIBRARY)" >>"${lib}/Android.mk"
      - cd ../../../../
      - ./autogen.sh
      - ./configure --disable-defaults --verbose
      - make dist -j $(nproc)
    ndk: 26.1.10909125
```

can you test this APK? [org.strongswan.android_82.apk.ZIP](https://github.com/strongswan/strongswan/files/14539803/org.strongswan.android_82.apk.ZIP) _(remove `.ZIP` from name)_
